data:
  customers_dataset: "data/1_-_customers.csv"
  indicators_dataset: "data/1_-_indicators.csv"

inferences_output_file: data/predictions.csv
model:
  grid_search_params:
   - pipeline__classifier: ["SVC()"]
     pipeline__classifier__C: !!python/tuple [0.000001, 1000000.0, 'log-uniform']
     pipeline__classifier__gamma: !!python/tuple [0.000001, 10.0, 'log-uniform']
     pipeline__classifier__degree: !!python/tuple [1,8]
     pipeline__classifier__kernel: ['linear', 'poly', 'rbf']
     #pipeline__features__balance_imputation: ['none','median']
   - pipeline__classifier: ["DecisionTreeClassifier()"]
     pipeline__classifier__criterion: ["gini", "entropy"]
     pipeline__classifier__max_depth: !!python/tuple [1,10]
     pipeline__classifier__min_samples_split: !!python/tuple [1,10]
     pipeline__classifier__min_samples_leaf: !!python/tuple [1,5]
     #pipeline__features__balance_imputation: ['none','median']
   - pipeline__classifier: ["RandomForestClassifier()"]
     pipeline__classifier__bootstrap: [True,False]
     pipeline__classifier__max_depth: !!python/tuple [10,100]
     pipeline__classifier__max_features: [2,3]
     pipeline__classifier__min_samples_leaf: !!python/tuple [2,50]
     pipeline__classifier__min_samples_split: !!python/tuple [5,15]
     pipeline__classifier__n_estimators: [500,1000,1500]
     #pipeline__features__balance_imputation: ['none','median']
   - pipeline__classifier: ["MLPClassifier()"]
     pipeline__classifier__hidden_layer_sizes: !!python/tuple [10,30,10]
     pipeline__classifier__activation: ['tanh', 'relu']
     pipeline__classifier__solver: ['sgd', 'adam']
     pipeline__classifier__alpha: !!python/tuple [0.0001, 0.5,'log-uniform']
     pipeline__classifier__learning_rate: ['constant','adaptive']
     #pipeline__features__balance_imputation: ['none','median']
   - pipeline__classifier: ["GradientBoostingClassifier()"]
     pipeline__classifier__loss: ["deviance"]
     pipeline__classifier__learning_rate: !!python/tuple [0.005, 0.5, 'log-uniform']
     pipeline__classifier__min_samples_split: !!python/tuple [0.1, 0.5, 'log-uniform']
     pipeline__classifier__min_samples_leaf: !!python/tuple [0.1, 0.5, 'log-uniform']
     pipeline__classifier__max_depth: [3,5,8]
     pipeline__classifier__max_features: ["log2","sqrt"]
     pipeline__classifier__criterion: ["friedman_mse",  "squared_error"]
     pipeline__classifier__subsample: [0.5,1.0,'log-uniform']
     pipeline__classifier__n_estimators: [10]
     #pipeline__features__balance_imputation: ['none','median']
   - pipeline__classifier: ["ExplainableBoostingClassifier()"]
     pipeline__classifier__binning: ['uniform','quantile','quantile_humanized']
     pipeline__classifier__outer_bags: !!python/tuple [2,10]
     pipeline__classifier__learning_rate: !!python/tuple [0.005, 0.5, 'log-uniform']
     pipeline__classifier__min_samples_leaf: !!python/tuple [2,10]
     pipeline__classifier__early_stopping_tolerance: !!python/tuple [0.0001,0.1,'log-uniform']
     #pipeline__features__balance_imputation: ['none','median']
