data:
  customers_dataset: "data/1_-_customers.csv"
  indicators_dataset: "data/1_-_indicators.csv"

inferences_output_file: data/predictions.csv
grid_search_params:
  - pipe__classifier: ["SVC()"]
    pipe__classifier__C: !!python/tuple [0.000001, 1000000.0, 'log-uniform']
    pipe__classifier__gamma: !!python/tuple [0.000001, 10.0, 'log-uniform']
    pipe__classifier__degree: !!python/tuple [1,8]
    pipe__classifier__kernel: ['linear', 'poly', 'rbf']
    pipe__features__balance_imputation: ['none','median']
  - pipe__classifier: ["DecisionTreeClassifier()"]
    pipe__classifier__criterion: ["gini", "entropy"]
    pipe__classifier__max_depth: !!python/tuple [1,10]
    pipe__classifier__min_samples_split: !!python/tuple [1,10]
    pipe__classifier__min_samples_leaf: !!python/tuple [1,5]
    pipe__features__balance_imputation: ['none','median']
  - pipe__classifier: ["RandomForestClassifier()"]
    pipe__classifier__bootstrap: [True,False]
    pipe__classifier__max_depth: !!python/tuple [10,100]
    pipe__classifier__max_features: [2,3]
    pipe__classifier__min_samples_leaf: !!python/tuple [2,50]
    pipe__classifier__min_samples_split: !!python/tuple [5,15]
    pipe__classifier__n_estimators: [500,1000,1500]
    pipe__features__balance_imputation: ['none','median']
  - pipe__classifier: ["MLPClassifier()"]
    pipe__classifier__hidden_layer_sizes: !!python/tuple [10,30,10]
    pipe__classifier__activation: ['tanh', 'relu']
    pipe__classifier__solver: ['sgd', 'adam']
    pipe__classifier__alpha: !!python/tuple [0.0001, 0.5,'log-uniform']
    pipe__classifier__learning_rate: ['constant','adaptive']
    pipe__features__balance_imputation: ['none','median']
  - pipe__classifier: ["GradientBoostingClassifier()"]
    pipe__classifier__loss: ["deviance"]
    pipe__classifier__learning_rate: !!python/tuple [0.005, 0.5, 'log-uniform']
    pipe__classifier__min_samples_split: !!python/tuple [0.1, 0.5, 'log-uniform']
    pipe__classifier__min_samples_leaf: !!python/tuple [0.1, 0.5, 'log-uniform']
    pipe__classifier__max_depth: [3,5,8]
    pipe__classifier__max_features: ["log2","sqrt"]
    pipe__classifier__criterion: ["friedman_mse",  "squared_error"]
    pipe__classifier__subsample: [0.5,1.0,'log-uniform']
    pipe__classifier__n_estimators: [10]
    pipe__features__balance_imputation: ['none','median']
  - pipe__classifier: ["ExplainableBoostingClassifier()"]
    pipe__classifier__binning: ['uniform','quantile','quantile_humanized']
    pipe__classifier__outer_bags: !!python/tuple [2,10]
    pipe__classifier__learning_rate: !!python/tuple [0.005, 0.5, 'log-uniform']
    pipe__classifier__min_samples_leaf: !!python/tuple [2,10]
    pipe__classifier__early_stopping_tolerance: !!python/tuple [0.0001,0.1,'log-uniform']
    pipe__features__balance_imputation: ['none','median']
