model_parameters:
- pipe__classifier:
  - ExplainableBoostingClassifier()
  pipe__classifier__binning: uniform
  pipe__classifier__early_stopping_tolerance: 0.004057047992283433
  pipe__classifier__learning_rate: 0.011234030199095161
  pipe__classifier__min_samples_leaf: 2
  pipe__classifier__outer_bags: 6
  pipe__features__imputer__balance_imputation: none
