model_parameters:
- pipe__classifier:
  - ExplainableBoostingClassifier()
  pipe__classifier__binning: quantile_humanized
  pipe__classifier__early_stopping_tolerance: 0.06289324408100383
  pipe__classifier__learning_rate: 0.02140765964038173
  pipe__classifier__min_samples_leaf: 7
  pipe__classifier__outer_bags: 5
